FROM tensorflow/tensorflow:2.19.0-gpu-jupyter

# Install additional Python packages
RUN pip install --no-cache-dir \
    pandas \
    scikit-learn \
    matplotlib \
    seaborn \
    numpy \
    scipy \
    jupyterlab